# Generated by Django 3.2.5 on 2021-07-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=32)),
                ('salt', models.CharField(max_length=32)),
                ('login_password', models.CharField(max_length=64)),
            ],
        ),
    ]
